### ISSUE TITLE
Presentation of newt Wednesday

### ISSUE THREAD

**Issue by ghost** [ikerito7/Bacchus-R1#12]
Hi guys! I have just updated the meeting minute of this afternoon. Please check it out (and sign it!)
I also posted an Atom screenshot in the "Picture" file of our Teambition folder.
Tell me if it looks ok for you, thanks!

As a summary:
I will now work on the content of Slide 3
Iker and Melinda work on the content of Slide 4
Max works on Slide 5 (putting Matthias' Canva into PPT form)

Slides 1,2,6 and 7 will be easy to make.

Marie

**Comment by ghost** [comment]
Hi guys!
I have just uploaded a Word file on Teambition called "GMS references.docx", where I compiled all the references we used so far. I tried to sort them in different sections but it might not be perfect yet.

As for the useful data we can put in our presentation, I would suggest 2 parts of what I wrote in it:
=> 75 references links on our GitHub platform
Mainly from FAO reports, articles, company websites, but also videos (youtube, TED talks)
=> Internet researches in English, Spanish, Indonesian and French
=> Contacts in Tiny Farm and RISE association to work with us

Maybe we should also include our big fields of research (edible insects in general, but also crickets, mealworms, beetles, health issues, legal issues, existing companies in the different markets, acceptance by Westerners...) To show that we tried to cover most of the aspects of our topic

**Comment by melindatjia** [comment]
I pushed the ppt half done, some changes needed as it can be seen in the comment box inside the ppt

**Comment by ghost** [comment]
How can I access it? I can only open the logo choice file...

**Comment by melindatjia** [comment]
https://github.com/ikerito7/Bacchus-R1 when you open the 2nd presentation file, click "Raw" to download it. I upload it also in the teambition bachus to make it easier

**Comment by ghost** [comment]
Ok I could access it, thanks!
Good job, looks nice!

Just a few remarks: 
Slide 2: I found a picture of Matthias on LinkedIn that you can probably use: https://www.linkedin.com/in/matthiasfloru

As for the numbers on slide 3, I already bothered counting the references links we used on Github and sorted them in categories (see GMS references.docx document I posted on our Teambition Bacchus file). 
There are 75 of them and I don't really want to open them all to count how many are reports, how many articles and how many company websites...

So maybe we could just write down something like
"75 reference links" (and say it is on our GitHub issues)
"researches in 4 languages"
"8 meeting minute" because that's the number we'll have reached by the presentation
"2 (or 3) contacts" -it depends on whether we count the person Melinda contacted for the report on mealworms or not.

What does "amount consumes" mean (and the related percentages refer to) on Slide 5?
Also, you put "more GHG and ammonia / kg" for crickets but on the graphics we can see that crickets release less GHG than mealworms (although they release more ammonia), 

On slide 6, I think we should precise "sport supplement" in the little text related to it on the right

"team members" appears twice on slide 8 ; is it my PPT version doing odd things ?

There is nothing on Slide 9 (yet ?)

**Comment by ghost** [comment]
Nice job to everybody. 
Next time we shall be careful to specify well our sources, but otherwise it seemed cool.
I'll close this issue!
