### ISSUE TITLE
links week 10

### ISSUE THREAD

**Issue by MFloru** [ikerito7/Bacchus-R1#19]
A blog posting news about insects for food

http://www.scoop.it/t/protein-alternatives-insects-as-mini-livstock

**Comment by MFloru** [comment]
Extensive report about global meat production and the economic/environmental consequences

Very helpful to write parts about branding our insects as better than traditional meat

https://www.foeeurope.org/sites/default/files/publications/foee_hbf_meatatlas_jan2014.pdf

**Comment by ghost** [comment]
Is there anything already written on the reasons why mealworms rock? If so, please post in on Github (or tell me where to find it ^^)

I think we can directly cite this article which is largely used in the FAO report, about mealworms Energy consumption, Global Warming Impact and Land use:

Environmental Impact of the Production of Mealworms as a Protein Source for Humans – A Life Cycle Assessment
    Dennis G. A. B. Oonincx (the name will probably be familiar to you ^^)
http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0051145

**Comment by ikerito7** [comment]
Belgium is doing it already
http://rt.com/news/188844-belgium-food-insects-products/

**Comment by ikerito7** [comment]
And Chinese austronauts too
http://rt.com/news/161004-china-space-worms-capsule/

**Comment by ikerito7** [comment]
List of Manufacturers (in Alibaba)
http://www.alibaba.com/corporations/mealworms/CID100006215.html

**Comment by ikerito7** [comment]
Check this company, they already make some products as we discussed earlier they have even chocolate with mealworms

http://www.greenkow.be/EN

**Comment by ikerito7** [comment]
They also sell a lot of bug variety, even chocolate dipped crickets and mealworms. Check them out
http://www.edibleunique.com

**Comment by ikerito7** [comment]
Another competitor; BBQ flavor mealwrorms, to be honest I woudl really like to try this ones
http://www.bush-grub.co.uk/home/14-bbq-meal-worms.html

**Comment by ikerito7** [comment]
Suppliers of pet food mealworms
http://www.mealworms-online.com/dried-mealworms/?sort=pricedesc
http://www.thenaturesway.com
http://www.sx-mealworms.com/e_products/?big_id=10

**Comment by ikerito7** [comment]
Article about how they have been problems in Spain when selling bugs
http://www.ipsnews.net/2013/07/edible-insect-market-hindered-by-legal-and-cultural-barriers-in-spain/
