### ISSUE TITLE
Welcoming Max

### ISSUE THREAD

**Issue by ghost** [ikerito7/Bacchus-R1#3]
Hi guys !
@ikerito7 :
Could you invite our new team-member to be a collaborator to this repo? 
It seems to me that I can't access the Settings as I am not the initial owner of this repo.
His Git pseudo is Maxi1989
Thanks in advance!

[I have just added him to our teambition group, by the way]

See you tomorrow (and let's keep in touch here by then)!

**Comment by ikerito7** [comment]
Done

**Comment by Maxi1989** [comment]
thanks
