### ISSUE TITLE
Deciding on a weekly meeting (Excel to fill, thanks!) - Done: Meeting at 9AM on Wednesdays

### ISSUE THREAD

**Issue by ghost** [ikerito7/Bacchus-R1#5]
Hi guys! 
I think we should meet every week to keep each other updated about what we did and decide on what remains to be done.

To know clearly about each other availability, I just created an excel file and put in in Teambition, "Files/Decide on our weekly meetings".

Please fill it like I did:
Green = normally always available
Orange = Can become available if needs really be
Red = No way to be available (other class)

As the hours I put are quite randomly, you can also specify from/until when you are available in the suggested hours (cf example in my column).

This kind of schedule is useful in case we have to reschedule a weekly meeting because a member is not there at usual time in a week.

Please let me know on this post if you have filled the file successfully!

**Comment by MFloru** [comment]
I updated mine. Personally, I think the thursday afternoon meeting time is the best as it is fast after class so we know immediately what to do.

**Comment by ghost** [comment]
Hi guys!
@ Max: Thanks for filling in the excel file "Files/Decide on our weekly meetings" on teambition, you're the last one :-).

As far as I can see, our weekly meeting will probably occur on Friday afternoons, 4:30PM; which is so far the only moment when all of us are available.
We shall discuss and arrange it when we meet this afternoon.
