### ISSUE TITLE
Link to references week#4

### ISSUE THREAD

**Issue by ghost** [ikerito7/Bacchus-R1#8]
Hey guys! We should be writing on the week 4 references!

I found a study on the insects contents.
http://onlinelibrary.wiley.com/doi/10.1002/mnfr.201200735/epdf

Last part (on a page numbered 820, just before the conclusion and references) is about the possible bad impacts on health.
There are several sorts of risks;
- allergies (like for crustaceans) and digestibility of the chitine (part of the exo-skeleton) + other possible bad substance in insects.
- micro-organisms on insects
- heavy metals and other bad substances (because of pesticides for example).

This matter has to be further scientifically investigate, though. I think that is the reason why insects mass consumption develops so slowly...

**Comment by MFloru** [comment]
Benefits & production process cricket flour 

This article, again about tiny farms (by far, they are the best in marketing themselves of all insect companies) gives the benefits of cricket flour. Also, it gives a functional description of the production process of raising crickets and states their food source today : chicken feed!

http://www.foodnavigator-usa.com/R-D/Tiny-Farms-Edible-insects-will-be-be-mainstream-in-future?nocount
